name: deploy-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
    permissions:
      users:
        - github-actions
        - cakraocha
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
        default: 'latest'
      container_update:
        description: 'Update container image'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo 'deploying...'
          sleep 5
          echo '(fake) deploy is done!'
