name: deploy-dev

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo '(fake) deploy is done!'

