# name: deploy-staging

# on:
#   # workflow_run:
#   #   workflows: [deploy-dev]
#   #   types:
#   #     - completed
#   push:
#     branches:
#       - staging

# permissions: write-all

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Deploy
#         run: |
#           echo 'deploying...'
#           sleep 5
#           echo '(fake) deploy staging is done!'

