name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'SHA of the commit to run the workflow on'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      # Add more steps here to run your workflow on the specific commit

      - name: Run Workflow
        run: |
          echo "Running workflow on commit ${{ github.event.inputs.commit_sha }}"
