name: deploy-prod

on:
  push:
    branches:
      - deploy

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo '(fake) deploy is done!'

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./autotag.sh

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          echo 'Pushing version $IMAGE_TAG'
