name: deploy-dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo 'deploying...'
          sleep 5
          echo '(fake) deploy is done!'
