name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag to re-deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag_name }}
      # Add more steps here to run your workflow on the specific commit

      - name: Run Workflow
        run: |
          cat .github/workflows/deploy-dev.yaml
